### ISSUE TITLE
Retrieving Place details

### ISSUE THREAD

**Issue by thTonmoy** [T-S-M/app#1]
- [x] Create a new activity and Name it PlaceDetailActivity
- [x] Create xml layout while creating the activity with android studio wizard
- [x] Retrieve location(Place Object) when a place is selected (from search result autocomplete)
- [x] Create intent to launch PlaceDetailActivity and pass the place id
- [x] use [Places API detail]( https://developers.google.com/places/android-api/place-details) to complete it (finish layout, show info)

**Comment by Sakib2263** [comment]
Done already ... need some improvement.
