### ISSUE TITLE
Internal changes

### ISSUE THREAD

**Issue by thTonmoy** [T-S-M/app#6]
- [ ] Separate Map in another activity

- [ ]  Use Place picker widget in discover

**Comment by Sakib2263** [comment]
Oka I will do ..soon

**Comment by thTonmoy** [comment]
place-picker is always full screen, no way to reduce height. Take a look at this instead. Can we use this approach with map?

[Code Example link](https://gist.github.com/dadino/d0b3acba08163749ee9c)
